language: go

os:
  - linux
  - windows
  - osx

go:
  - "1.11"
  - "1.10"
  - "1.9"

install:
  - go get github.com/go-chi/chi
  - go get github.com/sirupsen/logrus
  - go get github.com/unrolled/render

script:
  - go test github.com/omarhach/goimage
  - go test github.com/omarhach/goimage/utils
  - go build github.com/omarhach/goimage/api/cmd