language: go

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64

go:
  - master
  - 1.7
  - 1.6

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/csrf

before_script:
  - go fmt
  - go fmt github.com/Omar-H/goimage/util

script: go test && go test github.com/Omar-H/goimage/util