language: go

os:
  - linux

go:
  - 1.9

install:
  - go get github.com/go-chi/chi
  - go get github.com/sirupsen/logrus
  - go get github.com/gorilla/csrf

script:
  - go test github.com/omar-h/goimage
  - go test github.com/omar-h/goimage/utils
  - go test github.com/omar-h/goimage/cmd/goimage
  - go build github.com/omar-h/goimage/cmd/goimage
