language: go

os:
  - linux
  - windows
  - osx

go:
  - "1.11"
  - "1.10"
  - "1.9"

install:
  - go get -t -v ./...

script:
  - go test github.com/omarhachach/goimage
  - go test github.com/omarhachach/goimage/utils
  - go build github.com/omarhachach/goimage/api/cmd