language: go

os:
  - linux
  - windows
  - os_x

go:
  - 1.8
  - 1.7.3 

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/csrf

before_script:
  - go fmt github.com/Omar-H/goimage
  - go fmt github.com/Omar-H/goimage/util

script:
  - go test github.com/Omar-H/goimage
  - go test github.com/Omar-H/goimage/util
  - go build github.com/Omar-H/goimage
  - go build github.com/Omar-H/goimage/util