language: go

os:
  - linux

go:
  - 1.8.3
  - 1.7.6

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/csrf

before_script:
  - gofmt github.com/omar-h/goimage
  - gofmt github.com/omar-h/goimage/util

script:
  - go test github.com/omar-h/goimage
  - go test github.com/omar-h/goimage/util
  - go build github.com/omar-h/goimage
  - go build github.com/omar-h/goimage/util
